---
title: Files
description: Copies pebbleOS files
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: 'Delete Temp files'}

  - !file: {path: 'C:\PerfLogs'}
  - !cmd: {command: 'for /f %a in (''dir /b "%TEMP%" /a:d ^| findstr /v /c:"AME"'') do rmdir /q /s "%TEMP%\%a"'}
  - !cmd: {command: 'for /f %a in (''dir /b "%TEMP%" /a:-d'') do del /q "%TEMP%\%a"'}
  - !file: {path: 'C:\Temp'}
  - !file: {path: 'C:\Users\Public\Documents\Downloaded Installations'}
