---
title: Services
description: Configure Services
privilege: TrustedInstaller
actions:
  # TODO: Human readable names
  - !writeStatus: {status: 'Configure Services'}

  - !taskKill: {name: 'SecurityHealthService'}
  - !taskKill: {name: 'SecurityHealthSystray'}

  - !service: {name: 'AarSvc', operation: change, startup: 4}
  - !service: {name: 'AJRouter', operation: change, startup: 4}
  - !service: {name: 'AssignedAccessManagerSvc', operation: change, startup: 4}
  - !service: {name: 'bam', operation: change, startup: 4}
  - !service: {name: 'Beep', operation: change, startup: 4}
  # - !service: {name: 'CryptSvc', operation: change, startup: 3} # debut: sus?
  - !service: {name: 'dam', operation: change, startup: 4}
  - !service: {name: 'diagnosticshub.standardcollector.service', operation: change, startup: 4}
  - !service: {name: 'diagsvc', operation: change, startup: 4}
  - !service: {name: 'DiagTrack', operation: change, startup: 4}
  - !service: {name: 'DispBrokerDesktopSvc', operation: change, startup: 4}
  - !service: {name: 'DisplayEnhancementService', operation: change, startup: 4}
  - !service: {name: 'DPS', operation: change, startup: 4}
  - !service: {name: 'embeddedmode', operation: change, startup: 4}
  - !service: {name: 'fdPHost', operation: change, startup: 4}
  - !service: {name: 'FDResPub', operation: change, startup: 4}
  - !service: {name: 'fhsvc', operation: change, startup: 4}
  - !service: {name: 'GraphicsPerfSvc', operation: change, startup: 4}
  - !service: {name: 'LanmanServer', operation: change, startup: 4}
  - !service: {name: 'lfsvc', operation: change, startup: 3} # Note: Nice to have for programs like Auto Dark
  - !service: {name: 'MapsBroker', operation: change, startup: 4}
  - !service: {name: 'MessagingService', operation: change, startup: 4}
  - !service: {name: 'MsSecCore', operation: change, startup: 4}
  - !service: {name: 'MsSecFlt', operation: change, startup: 4}
  - !service: {name: 'Ndu', operation: change, startup: 4}
  - !service: {name: 'NetBT', operation: change, startup: 4}
  - !service: {name: 'PcaSvc', operation: change, startup: 4}
  - !service: {name: 'PeerDistSvc', operation: change, startup: 4}
  - !service: {name: 'PhoneSvc', operation: change, startup: 4}
  - !service: {name: 'RasMan', operation: change, startup: 4}
  - !service: {name: 'rdbss', operation: change, startup: 3}
  - !service: {name: 'rdyboost', operation: change, startup: 4}
  - !service: {name: 'RemoteAccess', operation: change, startup: 4}
  - !service: {name: 'RemoteRegistry', operation: change, startup: 4}
  - !service: {name: 'RetailDemo', operation: change, startup: 4}
  - !service: {name: 'SecurityHealthService', operation: change, startup: 4}
  - !service: {name: 'SEMgrSvc', operation: change, startup: 4}
  - !service: {name: 'Sense', operation: change, startup: 4}
  - !service: {name: 'SgrmAgent', operation: change, startup: 4}
  - !service: {name: 'SgrmBroker', operation: change, startup: 4}
  - !service: {name: 'SharedAccess', operation: change, startup: 4}
  # - !service: {name: 'ShellHWDetection', operation: change, startup: 4}
  - !service: {name: 'SmsRouter', operation: change, startup: 4}
  - !service: {name: 'Spooler', operation: change, startup: 4}
  - !service: {name: 'SstpSvc', operation: change, startup: 4}
  - !service: {name: 'SysMain', operation: change, startup: 4}
  - !service: {name: 'Telemetry', operation: change, startup: 4}
  - !service: {name: 'Themes', operation: change, startup: 4}
  # Disabled logs around this, breaks Windows Restore points
  # IMO I don't use - but others may.
  # - !service: {name: 'VSS', operation: change, startup: 4}
  # - !service: {name: 'wbengine', operation: change, startup: 4}
  - !service: {name: 'WdBoot', operation: change, startup: 4}
  - !service: {name: 'WdBoot', operation: change, startup: 4}
  - !service: {name: 'WdFilter', operation: change, startup: 4}
  - !service: {name: 'WdiServiceHost', operation: change, startup: 4}
  - !service: {name: 'WdiSystemHost', operation: change, startup: 4}
  - !service: {name: 'WdNisDrv', operation: change, startup: 4}
  - !service: {name: 'WdNisSvc', operation: change, startup: 4}
  - !service: {name: 'webthreatdefsvc', operation: change, startup: 4}
  - !service: {name: 'webthreatdefusersvc', operation: change, startup: 4}
  - !service: {name: 'webthreatdefusersvc*', operation: change, startup: 4}
  - !service: {name: 'WerSvc', operation: change, startup: 4}
  - !service: {name: 'wercplsupport', operation: change, startup: 4}
  - !service: {name: 'WinDefend', operation: change, startup: 4}
  - !service: {name: 'wisvc', operation: change, startup: 4}
  - !service: {name: 'wlpasvc', operation: change, startup: 4}
  - !service: {name: 'wscsvc', operation: change, startup: 4}
  - !service: {name: 'WSearch', operation: change, startup: 4}
  # - !service: { name: "AppIDSvc", operation: change, startup: 4 } # DEBT: may be needed?
  # - !service: { name: "GpuEnergyDrv", operation: change, startup: 4 } # DEBT: sus?
  # - !service: { name: "sppsvc", operation: change, startup: 4 } # DEBT: sus?
  # - !service: { name: "UevAgentService", operation: change, startup: 4 } # DEBT: may be needed?

  - !writeStatus: {status: 'Configure Driver Services'}
  - !service: {name: '3ware', operation: change, startup: 4}
  - !service: {name: 'ADP80XX', operation: change, startup: 4}
  - !service: {name: 'AmdK8', operation: change, startup: 4}
  - !service: {name: 'arcsas', operation: change, startup: 4}
  - !service: {name: 'AsyncMac', operation: change, startup: 4}
  - !service: {name: 'bam', operation: change, startup: 4}
  - !service: {name: 'Beep', operation: change, startup: 4}
  # - !service: {name: 'bindflt', operation: change, startup: 4}
  - !service: {name: 'buttonconverter', operation: change, startup: 4}
  # - !service: {name: 'CAD', operation: change, startup: 4}
  - !service: {name: 'cdfs', operation: change, startup: 4}
  - !service: {name: 'cdrom', operation: change, startup: 4}
  - !service: {name: 'CimFS', operation: change, startup: 4}
  # - !service: {name: 'circlass', operation: change, startup: 4}
  # - !service: {name: 'cnghwassist', operation: change, startup: 4}
  # TODO: Seems important to have?
  # - !service: {name: 'CompositeBus', operation: change, startup: 4}
  # - !service: {name: 'Dfsc', operation: change, startup: 4}
  # - !service: {name: 'ErrDev', operation: change, startup: 4}
  - !service: {name: 'fdc', operation: change, startup: 4}
  - !service: {name: 'flpydisk', operation: change, startup: 4}
  # - !service: {name: 'gencounter', operation: change, startup: 4}
  # - !service: {name: 'Microsoft_Bluetooth_AvrcpTransport', operation: change, startup: 4}
  # - !service: {name: 'mrxsmb', operation: change, startup: 4}
  # Breaks lanmanworkstation, which is used by AMD Ryzen Master.
  # - !service: {name: 'mrxsmb20', operation: change, startup: 4}
  - !service: {name: 'NdisVirtualBus', operation: change, startup: 4}
  - !service: {name: 'nvraid', operation: change, startup: 4}
  - !service: {name: 'passthruparser', operation: change, startup: 4}
  # - !service: {name: 'pvhdparser', operation: change, startup: 4}
  # - !service: {name: 'RFCOMM', operation: change, startup: 4}
  - !service: {name: 'sfloppy', operation: change, startup: 4}
  - !service: {name: 'SiSRaid2', operation: change, startup: 4}
  - !service: {name: 'SiSRaid4', operation: change, startup: 4}
  # - !service: {name: 'spaceparser', operation: change, startup: 4}
  # - !service: {name: 'spaceport', operation: change, startup: 4}
  # - !service: {name: 'srv2', operation: change, startup: 4}
  # - !service: {name: 'storflt', operation: change, startup: 4}
  - !service: {name: 'Telemetry', operation: change, startup: 4}
  - !service: {name: 'udfs', operation: change, startup: 4}
  # TODO: Seems important to have?
  # - !service: {name: 'umbus', operation: change, startup: 4}
  # - !service: {name: 'VerifierExt', operation: change, startup: 4}
  # - !service: {name: 'vhdparser', operation: change, startup: 4}
  # - !service: {name: 'Vid', operation: change, startup: 4}
  # - !service: {name: 'vpci', operation: change, startup: 4}
  # - !service: {name: 'vsmraid', operation: change, startup: 4}
  # - !service: {name: 'VSTXRAID', operation: change, startup: 4}
  - !service: {name: 'wanarp', operation: change, startup: 4}
  # - !service: {name: 'WindowsTrustedRTProxy', operation: change, startup: 4}
  # - !service: { name: "Tcpip6", operation: change, startup: 3 }
  # - !service: { name: "tcpipreg", operation: change, startup: 4 }
  # - !service: { name: "wcnfs", operation: change, startup: 4 }
  # - !service: {name: 'KSecPkg', operation: change, startup: 4} # Debt: Maybe debt? sus?
